# Generated by Django 3.1.1 on 2020-09-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('presenter', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'branch',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollateralType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_desc', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'collateraltype',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('presenter', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birthday', models.DateField(default='1980-01-01')),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('hometown', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('current_address', models.TextField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(upload_to='customers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='InterestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('interest_type', models.CharField(choices=[('PERCENTAGE', 'Phần trăm'), ('CASH', 'VNĐ')], default='PERCENTAGE', max_length=10)),
                ('interest_basis', models.CharField(choices=[('DAILY', 'Theo ngày'), ('WEEKLY', 'Theo tuần'), ('MONTHLY', 'Theo tháng'), ('YEARLY', 'Theo năm')], default='YEARLY', max_length=11)),
            ],
            options={
                'db_table': 'interesttype',
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('TIN_CHAP', 'Tín chấp'), ('THE_CHAP', 'Thế chấp')], default='THE_CHAP', max_length=8)),
                ('limit_total', models.BigIntegerField(default=0)),
                ('limit_used', models.BigIntegerField(default=0)),
                ('limit_left', models.BigIntegerField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('value_date', models.DateField(auto_now=True)),
                ('expire_date', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
            options={
                'db_table': 'limit',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birthday', models.DateField(default='1980-01-01')),
                ('id_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('current_address', models.TextField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(upload_to='staffs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_id', models.ManyToManyField(to='api.Branch')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'db_table': 'staff',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_desc', models.CharField(max_length=200)),
                ('value_date', models.DateField(auto_now=True)),
                ('expire_date', models.DateField(auto_now=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('interest_rate', models.CharField(max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.interesttype')),
                ('limit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.limit')),
            ],
            options={
                'db_table': 'loan',
            },
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_name', models.CharField(max_length=200)),
                ('value_date', models.DateField(auto_now=True)),
                ('expire_date', models.DateField(auto_now=True)),
                ('col_value', models.BigIntegerField(default=0)),
                ('legal_info', models.TextField(blank=True, max_length=500, null=True)),
                ('actual_info', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('col_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.collateraltype')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('inputter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staff')),
            ],
            options={
                'db_table': 'collateral',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
    ]
