# Generated by Django 3.1.1 on 2020-09-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=500)),
                ('birth_day', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('current_address', models.TextField(blank=True, max_length=500, null=True)),
                ('photo', models.TextField(blank=True, max_length=500, null=True)),
                ('id_number', models.TextField(max_length=50)),
                ('phone_number', models.TextField(blank=True, max_length=50, null=True)),
                ('email', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(max_length=500)),
                ('store_name', models.TextField(max_length=500)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('presenter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.staff')),
            ],
            options={
                'db_table': 'store',
            },
        ),
    ]
