# Generated by Django 3.1.1 on 2020-09-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='limit_type',
            field=models.CharField(choices=[('TINCHAP', 'Tín chấp'), ('THECHAP', 'Thế chấp')], default='THECHAP', max_length=7),
        ),
    ]
