# Generated by Django 3.1.1 on 2020-09-21 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_limit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='col_value',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.CreateModel(
            name='CustomerLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_secure', models.CharField(default=0, max_length=12)),
                ('limit_unsecure', models.CharField(default=0, max_length=12)),
                ('limit_total', models.CharField(default=0, max_length=12)),
                ('limit_used', models.CharField(default=0, max_length=12)),
                ('limit_left', models.CharField(default=0, max_length=12)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
            options={
                'db_table': 'customerlimit',
            },
        ),
    ]
