# Generated by Django 3.1.1 on 2020-09-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200921_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='col_value',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerlimit',
            name='limit_left',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerlimit',
            name='limit_secure',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerlimit',
            name='limit_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerlimit',
            name='limit_unsecure',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerlimit',
            name='limit_used',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='limit',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
